//ATTUATORI
#define FILTRO 1
#define POMPA_OUT 49
#define POMPA_IN 48
#define ILLUMINAZIONE 40
#define RISCALDATORE 43
#define VENTOLA 44
//SENSORI
#define LIVELLO_ACQUA_1 A0
#define LIVELLO_ACQUA_2 A1
#define TEMPERATURA 10
#define LIVELLO_TANICA_1 24
#define LIVELLO_ACQUA_3 34
#define LIVELLO_ACQUA_4 36
#define LIVELLO_PH 42


